### PR TITLE
First draft of first R lesson

### PR DESCRIPTION
**Pull request by pschloss**
For #1 

TODO:

- [x] Render to make markdown files
- [x] Assessments
- [ ] Glossary
- [x] Confirm that we covered Day 1 learning goals
- [x] A lot of editing / removing of notes / confirm notes covered in text

Etherpad: https://pad.carpentries.org/umichswc_curriculum_sprint_2020_R1

### CODE REVIEW

**Comment by MrFlick** [comment]
I discovered a bit more energy this evening to finish off the outline. I tried to remove most of the extra/unstructured notes so hopefully things are a bit more clear and close to that 80% target. I think we now at least touch on all the topic we had discussed during our initial brainstorming session.

**Comment by zenalapp** [comment]
@courtneyarmour this is ready to review! The very last part isn't complete yet (extra stuff), and there might be a few TODOs still floating around. We might want to add a couple more assessments in the future, but I think we're good for now.

@kelly-sovacool we're having issues with the website build failing. Not sure why/what to do about it.

**Comment by MrFlick** [comment]
It looks like most of the build failures have come from duplicate code chunk names. Currently there are three chunks with the name "Objects". It may be easier to remove all code chunk names to prevent further possible problems, or to just rename those to something else. Not sure which you would prefer.

**Comment by kelly-sovacool** [comment]
> It looks like most of the build failures have come from duplicate code chunk names. Currently there are three chunks with the name "Objects". It may be easier to remove all code chunk names to prevent further possible problems, or to just rename those to something else. Not sure which you would prefer.

Though I wasn't involved in the development of this particular lesson, I'm a fan of code chunk names for easy navigation in R Markdown documents.

**Comment by kelly-sovacool** [comment]
> @kelly-sovacool we're having issues with the website build failing. Not sure why/what to do about it.

Whenever a gh-actions job fails you can see the error message when you click the `Details` link: 
image

**Pull request merged**
